_target_: src.models.components.partmae_v4.PARTMaskedAutoEncoderViT

img_size: 224
canonical_img_size: 512
max_scale_ratio: 6.0 # a bit more than the real value

patch_size: 16
in_chans: 3
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4
norm_layer:
  _target_: torch.nn.LayerNorm
  eps: 1e-6
  _partial_: true
mask_ratio: 0.75
pos_mask_ratio: 0.75

decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16

sampler: stratified_jittered
criterion: l1

alpha_t: 0.6
alpha_ts: 0.75
alpha_s: 0.8

