_target_: src.models.components.partmae_v6.PARTMaskedAutoEncoderViT

img_size: 224
canonical_img_size: 512
local_img_size: 96
max_scale_ratio: 6.0 # a bit more than the real value

patch_size: 16
in_chans: 3
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4
norm_layer:
  _target_: torch.nn.LayerNorm
  eps: 1e-6
  _partial_: true
mask_ratio: 0.75
pos_mask_ratio: 0.75
num_views: ???

# decoder
decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16

# projection head
proj_bottleneck_dim: 256

# pose head
apply_tanh: false
sampler: stratified_jittered

# losses

## multipliers
lambda_pose:  1.0

lambda_psmooth:  0
lambda_pcr: 0

lambda_ccr: 0
lambda_cinv: 0


# pose loss
criterion: l1

alpha_t: 0.5
alpha_ts: 0.8
alpha_s: 1.0

# patch losses (smoothness + coding rate)
sigma_yx: 0.09
sigma_hw: 0.3

# class losses (class invariance + class coding rate)
cr_eps: 0.1


# cosine loss
cos_eps: 1e-8