_target_: timm.scheduler.cosine_lr.CosineLRScheduler
_partial_: true
# t_initial=num_epochs,
t_initial: ???
# t_mul=getattr(args, 'lr_cycle_mul', 1.),
cycle_mul: 1.0
# lr_min=args.min_lr,
lr_min: 1e-6
# decay_rate=args.decay_rate,
# decay_rate: 0.1
cycle_decay: 0.1
# warmup_lr_init=args.warmup_lr,
warmup_lr_init: 1e-5
# warmup_t=args.warmup_epochs,
warmup_t: ???
# cycle_limit=getattr(args, 'lr_cycle_limit', 1),
cycle_limit: 1
# t_in_epochs=True,
t_in_epochs: False
# noise_range_t=noise_range,
noise_range_t: null
# noise_pct=getattr(args, 'lr_noise_pct', 0.67),
noise_pct: 0.67
# noise_std=getattr(args, 'lr_noise_std', 1.),
noise_std: 1.0
# noise_seed=getattr(args, 'seed', 42),
noise_seed: 42
# https://github.com/facebookresearch/deit/blob/main/main.py