# @package callbacks
defaults:
  - /callbacks/classification_ft/loggers/metric_logger
  - lr_monitor
  - early_stopping
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 1
  every_n_epochs: 20

early_stopping:
  monitor: "val/acc"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
